### ISSUE TITLE
BUG 2 Multi post on same contest

### ISSUE THREAD

**Issue by donkeez** [donkeezapp/donkeez#2]
if posting to multiple contests, when coming back to first posted pic, it shows original screen, and it s posible to re post another pic. The app does NOT allowed multiple post on a same contest. It's one post / user / contest. New post replace older post.

**Comment by donkeez** [comment]
Seems like purple random heart still there.

**Comment by kutakmir** [comment]
isn't it a different issue number?

**Comment by donkeez** [comment]
Looks closed. I can't reproduce it in app.
