### ISSUE TITLE
BUG 3 Vote main screen

### ISSUE THREAD

**Issue by donkeez** [donkeezapp/donkeez#3]
When scroll down on vote pictures are liked automatically or seems to be (it's a random showing pictures everytime you refresh the page). When scroll fast, pictures are changing, when liking a picture, other hearts become purple. It looks like not stable. sliding down fast shows same picture, then change after loading. If vote, many hearts turn purple even if not voted for it. It needs to load clearly, randomely,and vote one by one.

**Comment by donkeez** [comment]
In fact, i reproduced bug. When u scroll down fast, new pics does not have time to load. So it's old pictures loading. And if u already voted for these pics, it shows purple heart. When new pics loaded, they take the place of old pics, but heart still purple, even if u did not voted for them. I guess it s purple heart stay as old pic was here before, and u already voted for it.

**Comment by donkeez** [comment]
I was able to reproduce the bug

**Comment by kutakmir** [comment]
I see

**Comment by kutakmir** [comment]
Now upon the request retrieval the cell checks if the requested post is the same as the current one. Let's test it!
