### ISSUE TITLE
SDK facebook to run app install campaigns

### ISSUE THREAD

**Issue by donkeez** [donkeezapp/donkeez#5]
add Sdk facebook to run App Install campaigns with facebook ads (tuto Facebook
<img width="613" alt="capture d ecran 2016-09-19 a 15 54 07" src="https://cloud.githubusercontent.com/assets/22445493/18831871/6737c178-83e8-11e6-8ee8-9f7997260022.png">

**Comment by kutakmir** [comment]
it think this is resolved, isn't it?

**Comment by donkeez** [comment]
yep resolved.
